name: Backend - Build & test 

on:
  push:  # push on master with changes in this file or in backend folder
    branches: [ "master" ]
    paths:
    - '.github/workflows/monhundle-api-AutoDeployTrigger-8215305a-a404-4fc8-9526-9cfa302ad898.yml'
    - 'src/monhundle/**'
  pull_request: # all PR targeting master
    branches: [ "master" ]
  workflow_dispatch: # enable manual execution
  release:
    types: [published]  # Déclenche le workflow quand une release est publiée

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/monhundle 

    - name: Build
      run: dotnet build ./src/monhundle --no-restore

    - name: Test
      run: dotnet test ./src/monhundle --no-build --verbosity normal

  update-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/monhundle

    steps:
      - uses: actions/checkout@v4

      - name: Get latest release tag
        id: get_latest_release
        run: |
          # Utilise l'API GitHub pour récupérer le tag de la dernière release
          LATEST_RELEASE_TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
            jq -r '.tag_name')
          echo "Latest release tag: $LATEST_RELEASE_TAG"
          echo "LATEST_RELEASE_TAG=$LATEST_RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_AUTH_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push docker image
        run: |
          docker build -t brycur/monhundle:${{ vars.DOCKER_VERSION_TAG}} .
          docker tag brycur/monhundle:${{ steps.get_latest_release.outputs.LATEST_RELEASE_TAG }} brycur/monhundle:latest
          docker push brycur/monhundle:${{ vars.DOCKER_VERSION_TAG}}
          docker push brycur/monhundle:latest


