name: Frontend - Build & tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-check:
    name: Test and TypeScript Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend-web/monhundle-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'        
          cache-dependency-path: ./src/frontend-web/monhundle-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npx vue-tsc --noEmit --pretty

      - name: Run unit tests
        run: npm run test:unit

      - name: Build for production
        run: npm run build

  deploy-to-azure:
    name: Deploy Front to Azure
    needs: test-and-check
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend-web/monhundle-web
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string

      - name: Build and Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SEA_0C4F15B03 }}
          action: "upload"
          app_location: "./src/frontend-web/monhundle-web"
          output_location: "dist"